//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gravis.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
public partial class GravisLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, NUMBER=2, INTEGER=3, FLOAT=4, DOT=5, OPEN_PAREN=6, CLOSE_PAREN=7, 
		ASSIGN=8, RIGHT_SHIFT=9, ADD=10, MINUS=11, MUL=12, DIV=13, MOD=14, LESS_THAN=15, 
		GREATER_THAN=16, EQUALS=17, GT_EQ=18, LT_EQ=19, NOT_EQ=20, INPUT=21, OUTPUT=22, 
		IF=23, OPR=24, SUBSPACE=25, SELF=26, WHITESPACE=27, NAME=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "NUMBER", "INTEGER", "NON_ZERO_DIGIT", "DIGIT", "FLOAT", "INT_PART", 
		"FRACTION", "DOT", "OPEN_PAREN", "CLOSE_PAREN", "ASSIGN", "RIGHT_SHIFT", 
		"ADD", "MINUS", "MUL", "DIV", "MOD", "LESS_THAN", "GREATER_THAN", "EQUALS", 
		"GT_EQ", "LT_EQ", "NOT_EQ", "INPUT", "OUTPUT", "IF", "OPR", "SUBSPACE", 
		"SELF", "WHITESPACE", "SPACES", "COMMENT", "NAME", "ID_START", "ID_CONTINUE"
	};


	public GravisLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GravisLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'const'", null, null, null, "'.'", "'['", "']'", "'='", "'>>'", 
		"'+'", "'-'", "'*'", "'/'", "'%'", "'<'", "'>'", "'=='", "'>='", "'<='", 
		"'!='", "'input'", "'output'", "'if'", "'opr'", "'subspace'", "'self'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "NUMBER", "INTEGER", "FLOAT", "DOT", "OPEN_PAREN", "CLOSE_PAREN", 
		"ASSIGN", "RIGHT_SHIFT", "ADD", "MINUS", "MUL", "DIV", "MOD", "LESS_THAN", 
		"GREATER_THAN", "EQUALS", "GT_EQ", "LT_EQ", "NOT_EQ", "INPUT", "OUTPUT", 
		"IF", "OPR", "SUBSPACE", "SELF", "WHITESPACE", "NAME"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Gravis.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GravisLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xDC', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x5', '\x3', 'T', '\n', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\a', '\x4', 'X', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 
		'[', '\v', '\x4', '\x3', '\x4', '\x6', '\x4', '^', '\n', '\x4', '\r', 
		'\x4', '\xE', '\x4', '_', '\x5', '\x4', '\x62', '\n', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x6', '\b', 'l', '\n', '\b', '\r', '\b', '\xE', '\b', 
		'm', '\x3', '\t', '\x3', '\t', '\x6', '\t', 'r', '\n', '\t', '\r', '\t', 
		'\xE', '\t', 's', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x5', ' ', '\xBF', '\n', 
		' ', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x6', '!', '\xC4', '\n', '!', 
		'\r', '!', '\xE', '!', '\xC5', '\x3', '\"', '\x3', '\"', '\a', '\"', '\xCA', 
		'\n', '\"', '\f', '\"', '\xE', '\"', '\xCD', '\v', '\"', '\x3', '#', '\x3', 
		'#', '\a', '#', '\xD1', '\n', '#', '\f', '#', '\xE', '#', '\xD4', '\v', 
		'#', '\x3', '$', '\x5', '$', '\xD7', '\n', '$', '\x3', '%', '\x3', '%', 
		'\x5', '%', '\xDB', '\n', '%', '\x2', '\x2', '&', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x2', '\v', '\x2', '\r', '\x6', '\xF', '\x2', 
		'\x11', '\x2', '\x13', '\a', '\x15', '\b', '\x17', '\t', '\x19', '\n', 
		'\x1B', '\v', '\x1D', '\f', '\x1F', '\r', '!', '\xE', '#', '\xF', '%', 
		'\x10', '\'', '\x11', ')', '\x12', '+', '\x13', '-', '\x14', '/', '\x15', 
		'\x31', '\x16', '\x33', '\x17', '\x35', '\x18', '\x37', '\x19', '\x39', 
		'\x1A', ';', '\x1B', '=', '\x1C', '?', '\x1D', '\x41', '\x2', '\x43', 
		'\x2', '\x45', '\x1E', 'G', '\x2', 'I', '\x2', '\x3', '\x2', '\a', '\x3', 
		'\x2', '\x33', ';', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x4', '\x2', '\f', '\f', '\xE', '\xF', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x2', '\xDE', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'K', '\x3', '\x2', '\x2', '\x2', '\x5', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x61', '\x3', '\x2', '\x2', '\x2', '\t', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x65', '\x3', '\x2', '\x2', '\x2', '\r', 'g', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 'k', '\x3', '\x2', '\x2', '\x2', '\x11', 'o', 
		'\x3', '\x2', '\x2', '\x2', '\x13', 'u', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'w', '\x3', '\x2', '\x2', '\x2', '\x17', 'y', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '{', '\x3', '\x2', '\x2', '\x2', '\x1B', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x80', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x84', '\x3', '\x2', '\x2', '\x2', '#', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '%', '\x88', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', ')', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x8E', '\x3', '\x2', '\x2', '\x2', '-', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x94', '\x3', '\x2', '\x2', '\x2', '\x31', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x37', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xAA', '\x3', '\x2', '\x2', '\x2', ';', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xB7', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\x41', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xC7', '\x3', '\x2', '\x2', '\x2', '\x45', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', 'G', '\xD6', '\x3', '\x2', '\x2', '\x2', 'I', '\xDA', 
		'\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\x65', '\x2', '\x2', 'L', 
		'M', '\a', 'q', '\x2', '\x2', 'M', 'N', '\a', 'p', '\x2', '\x2', 'N', 
		'O', '\a', 'u', '\x2', '\x2', 'O', 'P', '\a', 'v', '\x2', '\x2', 'P', 
		'\x4', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x5', '\a', '\x4', '\x2', 
		'R', 'T', '\x5', '\r', '\a', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', '\x6', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'Y', '\x5', '\t', '\x5', '\x2', 'V', 'X', '\x5', '\v', '\x6', 
		'\x2', 'W', 'V', '\x3', '\x2', '\x2', '\x2', 'X', '[', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '\x62', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', 
		'\x2', '\x2', '\\', '^', '\a', '\x32', '\x2', '\x2', ']', '\\', '\x3', 
		'\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', '_', ']', '\x3', 
		'\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', '`', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x61', 'U', '\x3', '\x2', '\x2', '\x2', '\x61', 
		']', '\x3', '\x2', '\x2', '\x2', '\x62', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x64', '\t', '\x2', '\x2', '\x2', '\x64', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\x66', '\t', '\x3', '\x2', '\x2', '\x66', '\f', 
		'\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x5', '\xF', '\b', '\x2', 'h', 
		'i', '\x5', '\x11', '\t', '\x2', 'i', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'j', 'l', '\x5', '\v', '\x6', '\x2', 'k', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 'k', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'q', '\a', '\x30', '\x2', '\x2', 'p', 'r', '\x5', '\v', '\x6', 
		'\x2', 'q', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', 
		'\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', '\x2', 
		'\x2', 't', '\x12', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '\x30', 
		'\x2', '\x2', 'v', '\x14', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', 
		']', '\x2', '\x2', 'x', '\x16', '\x3', '\x2', '\x2', '\x2', 'y', 'z', 
		'\a', '_', '\x2', '\x2', 'z', '\x18', '\x3', '\x2', '\x2', '\x2', '{', 
		'|', '\a', '?', '\x2', '\x2', '|', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'}', '~', '\a', '@', '\x2', '\x2', '~', '\x7F', '\a', '@', '\x2', '\x2', 
		'\x7F', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', '-', 
		'\x2', '\x2', '\x81', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', 
		'\a', '/', '\x2', '\x2', '\x83', ' ', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\a', ',', '\x2', '\x2', '\x85', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x87', '\a', '\x31', '\x2', '\x2', '\x87', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x88', '\x89', '\a', '\'', '\x2', '\x2', '\x89', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', '>', '\x2', '\x2', '\x8B', 
		'(', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', '@', '\x2', '\x2', 
		'\x8D', '*', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '?', '\x2', 
		'\x2', '\x8F', '\x90', '\a', '?', '\x2', '\x2', '\x90', ',', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x92', '\a', '@', '\x2', '\x2', '\x92', '\x93', 
		'\a', '?', '\x2', '\x2', '\x93', '.', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x95', '\a', '>', '\x2', '\x2', '\x95', '\x96', '\a', '?', '\x2', '\x2', 
		'\x96', '\x30', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\a', '#', 
		'\x2', '\x2', '\x98', '\x99', '\a', '?', '\x2', '\x2', '\x99', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\a', 'k', '\x2', '\x2', '\x9B', 
		'\x9C', '\a', 'p', '\x2', '\x2', '\x9C', '\x9D', '\a', 'r', '\x2', '\x2', 
		'\x9D', '\x9E', '\a', 'w', '\x2', '\x2', '\x9E', '\x9F', '\a', 'v', '\x2', 
		'\x2', '\x9F', '\x34', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', 
		'q', '\x2', '\x2', '\xA1', '\xA2', '\a', 'w', '\x2', '\x2', '\xA2', '\xA3', 
		'\a', 'v', '\x2', '\x2', '\xA3', '\xA4', '\a', 'r', '\x2', '\x2', '\xA4', 
		'\xA5', '\a', 'w', '\x2', '\x2', '\xA5', '\xA6', '\a', 'v', '\x2', '\x2', 
		'\xA6', '\x36', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\a', 'k', 
		'\x2', '\x2', '\xA8', '\xA9', '\a', 'h', '\x2', '\x2', '\xA9', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\a', 'q', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', 'r', '\x2', '\x2', '\xAC', '\xAD', '\a', 't', '\x2', '\x2', 
		'\xAD', ':', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', 'u', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', 'w', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'\x64', '\x2', '\x2', '\xB1', '\xB2', '\a', 'u', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'r', '\x2', '\x2', '\xB3', '\xB4', '\a', '\x63', '\x2', 
		'\x2', '\xB4', '\xB5', '\a', '\x65', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'g', '\x2', '\x2', '\xB6', '<', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', 
		'\a', 'u', '\x2', '\x2', '\xB8', '\xB9', '\a', 'g', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', 'n', '\x2', '\x2', '\xBA', '\xBB', '\a', 'h', '\x2', '\x2', 
		'\xBB', '>', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBF', '\x5', '\x41', 
		'!', '\x2', '\xBD', '\xBF', '\x5', '\x43', '\"', '\x2', '\xBE', '\xBC', 
		'\x3', '\x2', '\x2', '\x2', '\xBE', '\xBD', '\x3', '\x2', '\x2', '\x2', 
		'\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\b', ' ', 
		'\x2', '\x2', '\xC1', '@', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC4', 
		'\t', '\x4', '\x2', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', 
		'\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\xC7', '\xCB', '\a', '%', '\x2', '\x2', '\xC8', 
		'\xCA', '\n', '\x5', '\x2', '\x2', '\xC9', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\xD2', '\x5', 'G', '$', '\x2', '\xCF', '\xD1', '\x5', 
		'I', '%', '\x2', '\xD0', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', '\x2', 
		'\xD2', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD3', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\xD4', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD7', 
		'\t', '\x6', '\x2', '\x2', '\xD6', '\xD5', '\x3', '\x2', '\x2', '\x2', 
		'\xD7', 'H', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xDB', '\x5', 'G', '$', 
		'\x2', '\xD9', '\xDB', '\t', '\x3', '\x2', '\x2', '\xDA', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\xDA', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'J', '\x3', '\x2', '\x2', '\x2', '\xF', '\x2', 'S', 'Y', '_', '\x61', 
		'm', 's', '\xBE', '\xC5', '\xCB', '\xD2', '\xD6', '\xDA', '\x3', '\b', 
		'\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
