//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gravis.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGravisListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class GravisBaseListener : IGravisListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.file_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile_input([NotNull] GravisParser.File_inputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.file_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile_input([NotNull] GravisParser.File_inputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] GravisParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] GravisParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.link_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLink_stmt([NotNull] GravisParser.Link_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.link_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLink_stmt([NotNull] GravisParser.Link_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.def_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDef_stmt([NotNull] GravisParser.Def_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.def_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDef_stmt([NotNull] GravisParser.Def_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.node_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNode_def([NotNull] GravisParser.Node_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.node_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNode_def([NotNull] GravisParser.Node_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.input_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_def([NotNull] GravisParser.Input_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.input_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_def([NotNull] GravisParser.Input_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.output_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput_def([NotNull] GravisParser.Output_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.output_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput_def([NotNull] GravisParser.Output_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.const_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_def([NotNull] GravisParser.Const_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.const_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_def([NotNull] GravisParser.Const_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.if_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_def([NotNull] GravisParser.If_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.if_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_def([NotNull] GravisParser.If_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.opr_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpr_def([NotNull] GravisParser.Opr_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.opr_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpr_def([NotNull] GravisParser.Opr_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.subspace_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubspace_def([NotNull] GravisParser.Subspace_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.subspace_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubspace_def([NotNull] GravisParser.Subspace_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.self_subspace_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelf_subspace_def([NotNull] GravisParser.Self_subspace_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.self_subspace_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelf_subspace_def([NotNull] GravisParser.Self_subspace_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.dotted_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotted_name([NotNull] GravisParser.Dotted_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.dotted_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotted_name([NotNull] GravisParser.Dotted_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.node_inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNode_inst([NotNull] GravisParser.Node_instContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.node_inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNode_inst([NotNull] GravisParser.Node_instContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.comp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_op([NotNull] GravisParser.Comp_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.comp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_op([NotNull] GravisParser.Comp_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GravisParser.arith_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArith_op([NotNull] GravisParser.Arith_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GravisParser.arith_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArith_op([NotNull] GravisParser.Arith_opContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
